// Package main is the entry point for the k6-quick CLI tool.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// Flags holds all parsed CLI values passed to generateScript.
type Flags struct {
	URL         string
	VUs         int
	Duration    string
	Iterations  int      // 0 = not set
	RPS         int      // 0 = closed model (default)
	Method      string
	Headers     []string // "Key: Value" format
	Body        string   // empty = null in script
	Thresholds  []string // "metric:expr" format
	PrintScript bool
}

// jsString returns a JSON-encoded string (double-quoted, injection-safe JS string literal).
// Uses encoding/json which handles quotes, backslashes, newlines, tabs, unicode, and
// control characters — making the result a valid, injection-proof JS string literal.
// HTML-escaping is disabled so characters like <, >, & are not mangled in the output.
func jsString(s string) string {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(s)
	// Encode appends a trailing newline — trim it.
	return strings.TrimRight(buf.String(), "\n")
}

// generateScript returns the complete k6 JS script as a string.
// Pure function: no I/O, no side effects. All user values encoded via json.Marshal.
func generateScript(f Flags) string {
	var b strings.Builder

	// Header comment (per CONTEXT.md Claude's Discretion).
	b.WriteString("// generated by k6-quick — save with --print-script to keep this script\n")
	b.WriteString("import http from \"k6/http\";\n")
	b.WriteString("\n")

	// Options block.
	b.WriteString("export const options = {\n")

	if f.RPS > 0 {
		// Open model: constant-arrival-rate scenario (D-04, QCK-03).
		b.WriteString("  scenarios: {\n")
		b.WriteString("    default: {\n")
		b.WriteString("      executor: \"constant-arrival-rate\",\n")
		fmt.Fprintf(&b, "      rate: %d,\n", f.RPS)
		b.WriteString("      timeUnit: \"1s\",\n")
		fmt.Fprintf(&b, "      duration: %s,\n", jsString(f.Duration))
		fmt.Fprintf(&b, "      preAllocatedVUs: %d,\n", f.VUs)
		fmt.Fprintf(&b, "      maxVUs: %d,\n", f.VUs*2)
		b.WriteString("    },\n")
		b.WriteString("  },\n")
	} else if f.Iterations > 0 {
		// Closed model with iterations (D-04): no duration.
		fmt.Fprintf(&b, "  vus: %d,\n", f.VUs)
		fmt.Fprintf(&b, "  iterations: %d,\n", f.Iterations)
	} else {
		// Default closed model: vus + duration.
		fmt.Fprintf(&b, "  vus: %d,\n", f.VUs)
		fmt.Fprintf(&b, "  duration: %s,\n", jsString(f.Duration))
	}

	// Thresholds block (D-05): parse, accumulate by metric, sort keys for determinism.
	if len(f.Thresholds) > 0 {
		threshMap := make(map[string][]string)
		for _, t := range f.Thresholds {
			parts := strings.SplitN(t, ":", 2)
			if len(parts) == 2 {
				metric := parts[0]
				expr := parts[1]
				threshMap[metric] = append(threshMap[metric], expr)
			}
		}
		// Sort keys for golden-file stability (Pitfall 2).
		keys := make([]string, 0, len(threshMap))
		for k := range threshMap {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		b.WriteString("  thresholds: {\n")
		for _, k := range keys {
			exprs := threshMap[k]
			// Build the JS array of expressions.
			exprParts := make([]string, 0, len(exprs))
			for _, e := range exprs {
				exprParts = append(exprParts, jsString(e))
			}
			fmt.Fprintf(&b, "    %s: [%s],\n", jsString(k), strings.Join(exprParts, ", "))
		}
		b.WriteString("  },\n")
	}

	b.WriteString("};\n")
	b.WriteString("\n")

	// Default function with http.request call.
	b.WriteString("export default function () {\n")

	// Body expression: null or JSON-encoded string (D-06, D-07).
	var bodyExpr string
	if f.Body == "" {
		bodyExpr = "null"
	} else {
		bodyExpr = jsString(f.Body)
	}

	// Headers: parse to map, marshal to JSON without HTML escaping (encoding/json sorts
	// map keys automatically — Pitfall 2). HTML-escaping disabled to preserve characters
	// like < and > that may appear in header values.
	headersMap, _ := parseHeaders(f.Headers)
	var hBuf bytes.Buffer
	hEnc := json.NewEncoder(&hBuf)
	hEnc.SetEscapeHTML(false)
	_ = hEnc.Encode(headersMap)
	headersExpr := strings.TrimRight(hBuf.String(), "\n")

	fmt.Fprintf(&b, "  http.request(%s, %s, %s, { headers: %s });\n",
		jsString(f.Method),
		jsString(f.URL),
		bodyExpr,
		headersExpr,
	)

	b.WriteString("}\n")

	return b.String()
}
