// generated by k6-quick — save with --print-script to keep this script
import http from "k6/http";

export const options = {
  vus: 50,
  duration: "60s",
};

export default function () {
  http.request("POST", "https://api.example.com/health", null, { headers: {} });
}
