// generated by k6-quick — save with --print-script to keep this script
import http from "k6/http";

export const options = {
  vus: 10,
  duration: "30s",
};

export default function () {
  http.request("POST", "https://example.com/api", "{\"name\":\"test\"}", { headers: {"Authorization":"Bearer tok","Content-Type":"application/json"} });
}
