// generated by k6-quick — save with --print-script to keep this script
import http from "k6/http";

export const options = {
  vus: 5,
  iterations: 100,
};

export default function () {
  http.request("GET", "https://example.com", null, { headers: {} });
}
