// generated by k6-quick — save with --print-script to keep this script
import http from "k6/http";

export const options = {
  scenarios: {
    default: {
      executor: "constant-arrival-rate",
      rate: 50,
      timeUnit: "1s",
      duration: "30s",
      preAllocatedVUs: 10,
      maxVUs: 20,
    },
  },
};

export default function () {
  http.request("GET", "https://example.com", null, { headers: {} });
}
