// generated by k6-quick — save with --print-script to keep this script
import http from "k6/http";

export const options = {
  vus: 10,
  duration: "30s",
  thresholds: {
    "http_req_duration": ["p(95)<500", "p(99)<1000"],
    "http_req_failed": ["rate<0.01"],
  },
};

export default function () {
  http.request("GET", "https://example.com", null, { headers: {} });
}
